
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
    private global::Gtk.UIManager UIManager;
    
    private global::Gtk.Action FileAction;
    
    private global::Gtk.VBox vboxMain;
    
    private global::Gtk.MenuBar menubarMain;
    
    private global::Gtk.HBox hboxConnectionDetails;
    
    private global::Gtk.HBox hboxConnectionDetailsInner;
    
    private global::Gtk.HBox hbox3;
    
    private global::Gtk.Label lblHost;
    
    private global::Gtk.Entry entryHost;
    
    private global::Gtk.HBox hbox4;
    
    private global::Gtk.Label lblUsername;
    
    private global::Gtk.Entry entryUsername;
    
    private global::Gtk.HBox hbox5;
    
    private global::Gtk.Label lblPassword;
    
    private global::Gtk.Entry entryPassword;
    
    private global::Gtk.HBox hbox6;
    
    private global::Gtk.Label lblPort;
    
    private global::Gtk.SpinButton spinbtnPort;
    
    private global::Gtk.Button btnConnect;
    
    private global::Gtk.ScrolledWindow GtkScrolledWindow;
    
    private global::Gtk.TextView textviewLog;

    protected virtual void Build ()
    {
        global::Stetic.Gui.Initialize (this);
        // Widget MainWindow
        this.UIManager = new global::Gtk.UIManager ();
        global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
        this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
        this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
        w1.Add (this.FileAction, null);
        this.UIManager.InsertActionGroup (w1, 0);
        this.AddAccelGroup (this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
        this.WindowPosition = ((global::Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vboxMain = new global::Gtk.VBox ();
        this.vboxMain.Name = "vboxMain";
        this.vboxMain.Spacing = 6;
        // Container child vboxMain.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString ("<ui><menubar name=\'menubarMain\'><menu name=\'FileAction\' action=\'FileAction\'/></me" +
        "nubar></ui>");
        this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
        this.menubarMain.Name = "menubarMain";
        this.vboxMain.Add (this.menubarMain);
        global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menubarMain]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vboxMain.Gtk.Box+BoxChild
        this.hboxConnectionDetails = new global::Gtk.HBox ();
        this.hboxConnectionDetails.Name = "hboxConnectionDetails";
        this.hboxConnectionDetails.Spacing = 6;
        // Container child hboxConnectionDetails.Gtk.Box+BoxChild
        this.hboxConnectionDetailsInner = new global::Gtk.HBox ();
        this.hboxConnectionDetailsInner.Name = "hboxConnectionDetailsInner";
        this.hboxConnectionDetailsInner.Spacing = 6;
        // Container child hboxConnectionDetailsInner.Gtk.Box+BoxChild
        this.hbox3 = new global::Gtk.HBox ();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 2;
        // Container child hbox3.Gtk.Box+BoxChild
        this.lblHost = new global::Gtk.Label ();
        this.lblHost.Name = "lblHost";
        this.lblHost.LabelProp = global::Mono.Unix.Catalog.GetString ("Host:");
        this.hbox3.Add (this.lblHost);
        global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblHost]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.entryHost = new global::Gtk.Entry ();
        this.entryHost.WidthRequest = 100;
        this.entryHost.CanFocus = true;
        this.entryHost.Name = "entryHost";
        this.entryHost.IsEditable = true;
        this.entryHost.InvisibleChar = '●';
        this.hbox3.Add (this.entryHost);
        global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entryHost]));
        w4.Position = 1;
        this.hboxConnectionDetailsInner.Add (this.hbox3);
        global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxConnectionDetailsInner [this.hbox3]));
        w5.Position = 0;
        // Container child hboxConnectionDetailsInner.Gtk.Box+BoxChild
        this.hbox4 = new global::Gtk.HBox ();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 2;
        // Container child hbox4.Gtk.Box+BoxChild
        this.lblUsername = new global::Gtk.Label ();
        this.lblUsername.Name = "lblUsername";
        this.lblUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
        this.hbox4.Add (this.lblUsername);
        global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblUsername]));
        w6.Position = 0;
        w6.Expand = false;
        w6.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.entryUsername = new global::Gtk.Entry ();
        this.entryUsername.WidthRequest = 100;
        this.entryUsername.CanFocus = true;
        this.entryUsername.Name = "entryUsername";
        this.entryUsername.IsEditable = true;
        this.entryUsername.InvisibleChar = '●';
        this.hbox4.Add (this.entryUsername);
        global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryUsername]));
        w7.Position = 1;
        this.hboxConnectionDetailsInner.Add (this.hbox4);
        global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxConnectionDetailsInner [this.hbox4]));
        w8.Position = 1;
        w8.Expand = false;
        w8.Fill = false;
        // Container child hboxConnectionDetailsInner.Gtk.Box+BoxChild
        this.hbox5 = new global::Gtk.HBox ();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 2;
        // Container child hbox5.Gtk.Box+BoxChild
        this.lblPassword = new global::Gtk.Label ();
        this.lblPassword.Name = "lblPassword";
        this.lblPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
        this.hbox5.Add (this.lblPassword);
        global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblPassword]));
        w9.Position = 0;
        w9.Expand = false;
        w9.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.entryPassword = new global::Gtk.Entry ();
        this.entryPassword.WidthRequest = 100;
        this.entryPassword.CanFocus = true;
        this.entryPassword.Name = "entryPassword";
        this.entryPassword.IsEditable = true;
        this.entryPassword.InvisibleChar = '●';
        this.hbox5.Add (this.entryPassword);
        global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryPassword]));
        w10.Position = 1;
        this.hboxConnectionDetailsInner.Add (this.hbox5);
        global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxConnectionDetailsInner [this.hbox5]));
        w11.Position = 2;
        w11.Expand = false;
        w11.Fill = false;
        // Container child hboxConnectionDetailsInner.Gtk.Box+BoxChild
        this.hbox6 = new global::Gtk.HBox ();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 2;
        // Container child hbox6.Gtk.Box+BoxChild
        this.lblPort = new global::Gtk.Label ();
        this.lblPort.Name = "lblPort";
        this.lblPort.LabelProp = global::Mono.Unix.Catalog.GetString ("Port:");
        this.hbox6.Add (this.lblPort);
        global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblPort]));
        w12.Position = 0;
        w12.Expand = false;
        w12.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.spinbtnPort = new global::Gtk.SpinButton (0D, 65535D, 1D);
        this.spinbtnPort.WidthRequest = 75;
        this.spinbtnPort.CanFocus = true;
        this.spinbtnPort.Name = "spinbtnPort";
        this.spinbtnPort.Adjustment.PageIncrement = 10D;
        this.spinbtnPort.ClimbRate = 1D;
        this.spinbtnPort.Numeric = true;
        this.spinbtnPort.SnapToTicks = true;
        this.spinbtnPort.Value = 21D;
        this.spinbtnPort.Wrap = true;
        this.hbox6.Add (this.spinbtnPort);
        global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.spinbtnPort]));
        w13.Position = 1;
        w13.Expand = false;
        w13.Fill = false;
        this.hboxConnectionDetailsInner.Add (this.hbox6);
        global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxConnectionDetailsInner [this.hbox6]));
        w14.Position = 3;
        w14.Expand = false;
        w14.Fill = false;
        // Container child hboxConnectionDetailsInner.Gtk.Box+BoxChild
        this.btnConnect = new global::Gtk.Button ();
        this.btnConnect.CanFocus = true;
        this.btnConnect.Name = "btnConnect";
        this.btnConnect.UseUnderline = true;
        this.btnConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
        this.hboxConnectionDetailsInner.Add (this.btnConnect);
        global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxConnectionDetailsInner [this.btnConnect]));
        w15.Position = 4;
        w15.Expand = false;
        w15.Fill = false;
        this.hboxConnectionDetails.Add (this.hboxConnectionDetailsInner);
        global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxConnectionDetails [this.hboxConnectionDetailsInner]));
        w16.Position = 0;
        w16.Padding = ((uint)(6));
        this.vboxMain.Add (this.hboxConnectionDetails);
        global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxConnectionDetails]));
        w17.Position = 1;
        w17.Expand = false;
        w17.Fill = false;
        // Container child vboxMain.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.textviewLog = new global::Gtk.TextView ();
        this.textviewLog.CanFocus = true;
        this.textviewLog.Name = "textviewLog";
        this.textviewLog.Editable = false;
        this.GtkScrolledWindow.Add (this.textviewLog);
        this.vboxMain.Add (this.GtkScrolledWindow);
        global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.GtkScrolledWindow]));
        w19.Position = 2;
        this.Add (this.vboxMain);
        if ((this.Child != null)) {
            this.Child.ShowAll ();
        }
        this.DefaultWidth = 638;
        this.DefaultHeight = 504;
        this.Show ();
        this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
        this.btnConnect.Activated += new global::System.EventHandler (this.OnBtnConnectActivated);
        this.btnConnect.Clicked += new global::System.EventHandler (this.OnBtnConnectActivated);
    }
}
